Repository sergiodxa/remix-auth-oauth2, pull requests merged in 2024-08, with the labels that each got.

#105 Pass request to authorizationParams to support additional parameters
  README.md
  src/index.ts
Labels: enhancement

#108 Upgrade `@oslojs/oauth2` dependency
  bun.lockb
  package.json
  src/index.ts
  src/lib/authorization-code.ts
  src/lib/generator.ts
  src/lib/request.ts
  src/lib/token.ts
  src/test/helpers.ts
  src/test/mock.ts
  tsconfig.json
Labels: dependencies

#112 Correctly parse optional token response fields scope and refresh_token
  src/lib/token.ts
Labels: bug

#116 Consider expires_in as optional
  src/lib/token.ts
Labels: enhancement
